openapi: 3.0.0
info:
  title: Owner Statement Upload API
  version: 1.0.0
  description: API for uploading owner monthly statements

servers:
  - url: https://dicykpvquqrmiuzykhty.supabase.co/functions/v1/clearing-owner-statement

paths:
  /:
    post:
      summary: Upload owner statement
      security:
        - ClearingSecret: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_name
                - owner_name
                - statement_month
                - pdf_url
              properties:
                user_id:
                  type: string
                  description: Optional internal UUID
                user_name:
                  type: string
                owner_name:
                  type: string
                statement_month:
                  type: string
                  example: 2026-01
                pdf_url:
                  type: string
                  format: uri
      responses:
        "200":
          description: Statement stored successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: User not found
        "429":
          description: Rate limit exceeded
        "500":
          description: Internal server error

components:
  securitySchemes:
    ClearingSecret:
      type: apiKey
      in: header
      name: x-clearing-secret
