openapi: 3.0.3
info:
  title: Owner Statement Upload API
  version: 1.1.0
  description: API for securely uploading/updating owner monthly statements.

servers:
  - url: https://ojqzsxqkpxagknekhqke.supabase.co/functions/v1/clearing-owner-statement
    description: Supabase Edge Function endpoint

paths:
  /:
    post:
      summary: Upload owner statement
      description: |
        Stores an owner monthly statement PDF link.
        User is identified internally using user_name.
        Rate limited to 100 requests per minute.
      security:
        - ClearingSecret: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnerStatementRequest'
            example:
              user_name: "John Manager"
              owner_name: "John Owner"
              statement_month: "2026-02"
              pdf_url: "https://clearing.com/statements/67890.pdf"
              properties:
                - "Property A"
                - "Property B"
      responses:
        "200":
          description: Statement stored successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Bad request (missing or invalid fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized (invalid secret)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    ClearingSecret:
      type: apiKey
      in: header
      name: x-clearing-secret

  schemas:
    OwnerStatementRequest:
      type: object
      required:
        - user_name
        - owner_name
        - statement_month
        - pdf_url
        - properties
      properties:
        user_name:
          type: string
          description: Property manager’s full name
          example: "John Manager"

        owner_name:
          type: string
          description: Owner’s full name
          example: "John Owner"

        statement_month:
          type: string
          pattern: '^([0-9]{4})-(0[1-9]|1[0-2])$'
          description: Format YYYY-MM
          example: "2026-02"

        pdf_url:
          type: string
          format: uri
          description: Publicly accessible PDF link
          example: "https://clearing.com/statements/67890.pdf"

        properties:
          type: array
          description: List of properties included in the statement
          items:
            type: string
          example:
            - "Property A"
            - "Property B"

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Statement stored successfully"
        data:
          type: array
          items:
            type: object
            properties:
              user_name:
                type: string
              owner_name:
                type: string
              statement_month:
                type: string
              pdf_url:
                type: string
              properties:
                type: array
                items:
                  type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Missing required fields"
