openapi: 3.0.3
info:
  title: Owner Statement Upload API
  version: 1.0.0
  description: API for securely uploading/updating owner monthly statements.

servers:
  - url: https://dicykpvquqrmiuzykhty.supabase.co/functions/v1/clearing-owner-statement
    description: Supabase Edge Function endpoint

paths:
  /:
    post:
      summary: Upload owner statement
      description: |
        Stores  an owner monthly statement PDF link.
      security:
        - ClearingSecret: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnerStatementRequest'
            example:
              user_name: "John Manager"
              owner_name: "John Owner"
              statement_month: "2026-02"
              pdf_url: "https://clearing.com/statements/67890.pdf"
      responses:
        "200":
          description: Statement stored successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Bad request (missing or invalid fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized (invalid secret)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    ClearingSecret:
      type: apiKey
      in: header
      name: x-clearing-secret

  schemas:
    OwnerStatementRequest:
      type: object
      required:
        - user_name
        - owner_name
        - statement_month
        - pdf_url
      properties:
        user_name:
          type: string
          description: Property manager’s full name
        owner_name:
          type: string
          description: Owner’s full name
        statement_month:
          type: string
          pattern: '^([0-9]{4})-(0[1-9]|1[0-2])$'
        pdf_url:
          type: string
          format: uri
          description: Publicly accessible PDF link

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Statement stored successfully"
        data:
          type: array
          description: Inserted or updated statement records

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
